Reaper file/configuration sync update 09/13/2018 13:25:17

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -2,18 +2,63 @@ version: 2
 jobs:
   test:
     docker:
-      - image: hashicorp/terraform:0.11.7
+      - image: hashicorp/terraform:0.11.8
     steps:
+      - run: mkdir -p ~/branches/master
+      - run: cd ~/branches/master && GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=no' git clone $CIRCLE_REPOSITORY_URL .
       - checkout:
-            path: ~/module
-      - run: mkdir -p ~/workspace
+            path: ~/branches/${CIRCLE_BRANCH}
+      - run: mkdir -p ~/workspace/plan_results
+      - run: ln -s ~/branches/${CIRCLE_BRANCH} ~/module
+      - run: cp -pr ~/module/.circleci/templates ~/templates
       - run: cp -pr ~/module/.circleci/bin ~/bin
       - run: chmod +x ~/bin/*.sh
-      - run: mv ~/module/tests/ ~/layers/ # Move tests into layers directory
+      - run:
+          name: check tests for s3 backends
+          command: cd ~ && ~/bin/s3_backend_check.sh
+      - run:
+          name: switch symlink to master branch
+          command: cd ~ && ~/bin/check_master_tests.sh
+      - run: cp -pr ~/module/tests/ ~/layers/ # Move tests into layers directory
+      - run:
+          name: create tf s3 backends
+          command: cd ~ && ~/bin/create_s3.sh
+      - run:
+          name: plan master branch
+          command: cd ~ && ~/bin/plan.sh
+      - run:
+          name: apply master branch
+          command: cd ~ && ~/bin/apply.sh
+      - run:
+          name: switch symlink to branch
+          command: |
+            rm -f ~/module
+            ln -s ~/branches/${CIRCLE_BRANCH} ~/module
+      - run:
+          name: set up directories
+          command: |
+            cd ~ && ~/bin/branch_test_setup.sh
+      - run:
+          name: create tf s3 backends
+          command: cd ~ && ~/bin/create_s3.sh
       - run:
           name: lint tests
           command: cd ~ && ~/bin/lint.sh
-      - run: mkdir -p ~/example_lint/layers/ && mv ~/module/examples/ ~/example_lint/layers/
+      - run:
+          name: prep examples
+          command: |
+            mkdir -p ~/example_lint/layers/
+            if [ -d ~/module/examples/ ]; then
+              echo "Moving examples directory"
+              mv ~/module/examples/ ~/example_lint/layers/ || echo "Cannot move examples directory"
+            fi
+            if [ -d ~/module/modules/ ]; then
+              SUBMODULES=$(find ~/module/modules/* -type d -maxdepth 0 -exec basename '{}' \; | sort -n)
+              for MODULE in $SUBMODULES; do
+                echo "Moving $MODULE examples directory"
+                mv ~/module/modules/$MODULE/examples/ ~/example_lint/layers/$MODULE/
+              done
+            fi
       - run:
           name: lint examples
           command: cd ~/example_lint  && ~/bin/lint.sh
@@ -22,21 +67,45 @@ jobs:
           name: lint module
           command: cd ~/module_lint  && ~/bin/lint.sh
       - run:
-          name: plan
+          name: plan branch updates
           command: cd ~ && ~/bin/plan.sh
       - run:
-          name: apply
+          name: write plan destroy results
+          command: cd ~ && ~/bin/plan_check.sh
+      - run:
+          name: apply branch updates
           command: cd ~ && ~/bin/apply.sh
       - run:
           name: destroy
-          command: cd ~ && ~/bin/destroy.sh  # must succeed or we have something to clean up manually
+          command: cd ~ && ~/bin/destroy.sh && ~/bin/destroy_s3_buckets.sh # must succeed or we have something to clean up manually
           when: always
+      - persist_to_workspace:
+          root: ~/workspace
+          paths: plan_results/*
+  check_destruction:
+    docker:
+      - image: hashicorp/terraform:0.11.8
+    steps:
+      - attach_workspace:
+          at: ~/workspace
+      - checkout:
+            path: ~/module
+      - run: cp -pr ~/module/.circleci/bin ~/bin
+      - run:
+          name: raise errors if destroy detected
+          command: cd ~ && ~/bin/raise.sh
 
 workflows:
   version: 2
   build_and_test:
     jobs:
       - test:
+          filters:
+            branches:
+             ignore: master
+      - check_destruction:
+          requires:
+            - test
           filters:
             branches:
              ignore: master
